### PR TITLE
feat(app): add cors support

### PR DESCRIPTION
**Pull request by eseceve**
## Story
- Add CORS support

## TODO
- [x] Allow CORS
- [x] Read env vars: `PORT`, `DEBUG`, `RELOADER` and `PRINTER_WHITELIST`
- [x] Add _whitelist_ to allow a few Origins instead of `*`
- [x] Update readme
- [x] Tests are green

### CODE REVIEW

**Review by pdelsol — APPROVED** [review]
que lindo

**Comment by eseceve** [comment]
Ya funka stage ;)

**Comment by pdelsol** [comment]
go !

**Comment by eseceve** [comment]
Close because of https://github.com/admetricks/impress/pull/1

**Pull request closed without merging**
